### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by Luckyaremu**
#tic tac toe miles stone one

-set up folders and files needed
-Added string "hello world!"
-Added stickler and rubocop
Thank you for reviewing are project if you notice any corrections needed, kindly let us know.

kind regards

### CODE REVIEW

**Comment by kotoku-code** [comment]
we are getting this check fail from from the github stickler as you can see above.
"I couldn't find a .stickler.yml file in this repository. I can make one for you, or you can create one by following the documentation."
kindly note the following images showing we have added the the stickler file.



image

**Comment by kotoku-code** [comment]
https://microverse-students.slack.com/files/UR59X53V4/F0113HFKTD2/stickler.jpg

**Comment by kotoku-code** [comment]
stickler

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @Luckyaremu and @kotoku-code  :balloon: :lollipop: 

### Good job, I'm glad you were able to fix your linters :clap: :clap: :clap:  please fix the following:

* [ ] `main.rb` is [executable file](https://commandercoriander.net/blog/2013/02/16/making-a-ruby-script-executable/):
  * `#!/usr/bin/env ruby` is the top line
  * puts "Hello world" in the following line ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/execute_bin.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

- You print the "Hello world" but you are missing the line on top, let's add it to your main.rb file

### That's it! :raised_hands: 

### Please :pray: make the change :man_technologist: :man_technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

**Comment by kotoku-code** [comment]
thank you for feedback, we have added the requested line.

**Comment by shshamim63** [comment]
## Status :tada: Approved :tada: 
___
Hi @Luckyaremu and @kotoku-code :wave: ,
Congrats :clap: , you have made the change asked by the previous reviewer. So nothing is blocking me right at the moment.
___
#### This :+1: is from me. You can go-ahead and best of luck for your next milestone.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](linkedin.com/in/shakhawathossainshamim/) | [Twitter](https://twitter.com/Shshamim090)

**Pull request closed without merging**
